Fix sanity checking for member score (#300)
The check was causing exceptions in case there was no secondary
set due to the conditions before:

```
[ERROR] [MainProcess] [Main:exception:208] Failed to start oplog tailing threads! Error: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File ".../mongodb_consistent_backup/Main.py", line 363, in run
    self.oplogtailer.run()
  File ".../mongodb_consistent_backup/Oplog/Tailer/Tailer.py", line 56, in run
    secondary   = self.replsets[shard].find_secondary()
  File ".../mongodb_consistent_backup/Replication/Replset.py", line 259, in find_secondary
    if self.secondary['score'] == 0:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Added "is not None" to the check condition to ensure the score is only validated
if a secondary is actually set.